package net.zharok01.coralinesystems.client.particle;

import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.client.particle.*;
import net.minecraft.core.particles.SimpleParticleType;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

/**
 * A tinted liquid-droplet splash particle for the Brewing Cauldron.
 *
 * Physics model mirrors vanilla's DripParticle / FallAndLandParticle chain:
 *  - Launched with an outward+upward initial velocity (generated by the Provider).
 *  - Subject to real downward gravity (0.06f per tick), identical to DripParticle.
 *  - Air drag: xd/yd/zd *= 0.98 per tick (same as DripParticle.tick()).
 *  - Removed as soon as onGround becomes true (same as FallingParticle.postMoveUpdate).
 *
 * Color encoding: r/g/b are packed into the xSpeed/ySpeed/zSpeed slots of
 * Level#addParticle, exactly as before. The Provider reads them as colour and
 * generates real physics velocity from randomness, so the data channel is
 * unchanged from the previous implementation.
 *
 * Render type: PARTICLE_SHEET_OPAQUE, matching DripParticle (the Subtle
 * Effects SplashDropletParticle also uses this).
 */
@OnlyIn(Dist.CLIENT)
public class CauldronSplashParticle extends TextureSheetParticle {

    public static SimpleParticleType TYPE;

    // ── Constructor ──────────────────────────────────────────────────────────

    /**
     * @param r   red   component 0-1 (colour, not velocity)
     * @param g   green component 0-1
     * @param b   blue  component 0-1
     * @param vx  initial X velocity (outward scatter, generated by Provider)
     * @param vy  initial Y velocity (upward burst, generated by Provider)
     * @param vz  initial Z velocity (outward scatter, generated by Provider)
     */
    private CauldronSplashParticle(
            ClientLevel level,
            double x, double y, double z,
            float r, float g, float b,
            double vx, double vy, double vz,
            SpriteSet sprites) {
        super(level, x, y, z, vx, vy, vz);

        // ── Colour ───────────────────────────────────────────────────────────
        this.rCol = r;
        this.gCol = g;
        this.bCol = b;

        // ── Physics — mirrors DripParticle exactly ────────────────────────
        // DripParticle sets gravity = 0.06f in its constructor (via setSize).
        // TextureSheetParticle's default gravity is 0.04f; we override it.
        this.gravity = 0.06f;

        // Initial velocity from the Provider (outward + upward burst).
        this.xd = vx;
        this.yd = vy;
        this.zd = vz;

        // ── Lifetime ─────────────────────────────────────────────────────────
        // DripParticle.FallingParticle uses ~64 / rand(0.8+0.2) ≈ 71–320 ticks,
        // which is very long. For a splash effect we want something shorter.
        // We cap at ~20-40 ticks so the droplet lands quickly and removes itself.
        // GUESS: the exact lifetime range is a design judgement call.
        //    Adjust if the droplets need to travel further / shorter.
        this.lifetime = 20 + level.getRandom().nextInt(21);

        // ── Size ─────────────────────────────────────────────────────────────
        // SE's SplashDropletParticle calls setSize(scale * 1.5f) where
        // scale ≈ 1.0, giving a quadSize around 0.15. We match that range.
        // GUESS: exact quadSize tuned visually; adjust to taste.
        this.quadSize = 0.10f + level.getRandom().nextFloat() * 0.08f;

        this.setSpriteFromAge(sprites);
    }

    // ── TextureSheetParticle overrides ───────────────────────────────────────

    @Override
    public void tick() {
        // Save previous position for interpolation (required by TextureSheetParticle).
        this.xo = this.x;
        this.yo = this.y;
        this.zo = this.z;

        // Apply gravity — identical to DripParticle.tick().
        this.yd -= this.gravity;

        // Move (handles collision + sets this.onGround).
        this.move(this.xd, this.yd, this.zd);

        // Remove on ground contact — mirrors FallingParticle.postMoveUpdate().
        if (this.onGround) {
            this.remove();
            return;
        }

        // Air drag — identical to DripParticle.tick().
        this.xd *= 0.98f;
        this.yd *= 0.98f;
        this.zd *= 0.98f;

        // Remove if lifetime expired.
        if (this.age++ >= this.lifetime) {
            this.remove();
        }
    }

    @Override
    public ParticleRenderType getRenderType() {
        // PARTICLE_SHEET_OPAQUE matches DripParticle and SE's SplashDropletParticle.
        return ParticleRenderType.PARTICLE_SHEET_OPAQUE;
    }

    // ── Provider ─────────────────────────────────────────────────────────────

    @OnlyIn(Dist.CLIENT)
    public static class Provider implements ParticleProvider<SimpleParticleType> {

        private final SpriteSet sprites;

        public Provider(SpriteSet sprites) {
            this.sprites = sprites;
        }

        /**
         * xSpeed/ySpeed/zSpeed carry packed r/g/b colour (0-1 floats), NOT
         * physics velocity — same convention as before. Real launch velocity is
         * generated here from randomness, matching what SE's Provider does for
         * its SplashDropletParticle (outward scatter + upward burst).
         */
        @Override
        public Particle createParticle(
                SimpleParticleType type,
                ClientLevel level,
                double x, double y, double z,
                double xSpeed, double ySpeed, double zSpeed) {

            float r = (float) xSpeed;
            float g = (float) ySpeed;
            float b = (float) zSpeed;

            var rand = level.getRandom();

            // Outward scatter: random horizontal direction, moderate speed.
            // Matches SE SplashDropletParticle's velocity passed from its emitter.
            // GUESS: speed magnitudes tuned to look like a cauldron splash;
            //    adjust vx/vz range and vy if the spread feels too wide or too high.
            double vx = (rand.nextDouble() - 0.5) * 0.3;
            double vy = 0.1 + rand.nextDouble() * 0.2;   // upward burst
            double vz = (rand.nextDouble() - 0.5) * 0.3;

            return new CauldronSplashParticle(level, x, y, z, r, g, b, vx, vy, vz, sprites);
        }
    }
}