package net.zharok01.coralinesystems.datagen;

import net.minecraft.data.PackOutput;
import net.minecraftforge.client.model.generators.ItemModelBuilder;
import net.minecraftforge.client.model.generators.ItemModelProvider;
import net.minecraftforge.client.model.generators.ModelFile;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.zharok01.coralinesystems.CoralineSystems;

/**
 * Generates flat two-layer item models for all 10 drink items (5
 * substances x Bottle/Bucket), replacing 10 hand-written near-duplicate
 * JSON files -- proposed by Gemini per the roadmap (Section 1.6), agreed
 * on in the Session 3 design conversation once the actual vanilla
 * potion.json layer shape was confirmed (see
 * CoralineItemColors' class javadoc for the layer0/layer1 correction).
 * <p>
 * Model shape mirrors vanilla's {@code item/potion} model exactly:
 * {@code parent: "item/generated"}, {@code layer0} = the TINTED liquid
 * silhouette (tintIndex 0 -- see CoralineItemColors), {@code layer1} = the
 * UNTINTED container outline (glass bottle / metal bucket) drawn on top.
 * <p>
 * <b>Texture files this expects to already exist</b> (not generated by
 * this class -- datagen only writes the model JSON, never texture PNGs):
 * <ul>
 * <li>{@code assets/coraline_systems/textures/item/<name>_liquid.png} --
 * one per Bottle/Bucket pair (liquid silhouette differs in shape between
 * a Bottle and a Bucket, so this is NOT shared across the pair).
 * <li>{@code assets/coraline_systems/textures/item/<name>_outline.png} --
 * same silhouette-differs-by-container-type rule.
 * </ul>
 * These are art assets outside datagen's scope -- this class assumes
 * they'll be placed at those paths, and will produce models that fail to
 * resolve textures until they are. Flagged here rather than guessed at
 * with placeholder texture content.
 */
public class ModItemModelProvider extends ItemModelProvider {

    public ModItemModelProvider(PackOutput output, ExistingFileHelper existingFileHelper) {
        super(output, CoralineSystems.MOD_ID, existingFileHelper);
    }

    @Override
    protected void registerModels() {
        tintedDrink("mulberry_juice_bottle");
        tintedDrink("mulberry_juice_bucket");
        tintedDrink("wine_bottle");
        tintedDrink("wine_bucket");
        tintedDrink("tea_bottle");
        tintedDrink("tea_bucket");
        tintedDrink("kombucha_bottle");
        tintedDrink("kombucha_bucket");
        tintedDrink("dregs_bottle");
        tintedDrink("dregs_bucket");
    }

    /**
     * @param name the item's registry name, e.g. "wine_bottle" -- matches
     *             the string keys used in CoralineItems.java's register(...)
     *             calls (that class isn't referenced directly here; these
     *             are plain string literals kept in sync by hand against
     *             the 10 names registered there).
     */
    private void tintedDrink(String name) {
        ItemModelBuilder builder = getBuilder(name)
                .parent(new ModelFile.UncheckedModelFile("item/generated"))
                .texture("layer0", modLoc("item/" + name + "_liquid"))
                .texture("layer1", modLoc("item/" + name + "_outline"));
    }
}